- name: Install the latest version of Nginx Server
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Removing Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Creating Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Downloading FrontEnd Content and Extracting
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Copying Reverse Configuration file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Restarting Nginx Service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes